THPTChuyen/Models/GiaoVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public int MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TotNghiep { get; set; }
        public string ChuyenNganh { get; set; }
        public string CongTacNam { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaToChuc { get; set; }
        public string avatar { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual ToChuc ToChuc { get; set; }
    }
}

THPTChuyen/Areas/Admin/Controllers/GiaoViensController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using THPTChuyen.Models;
using static System.Net.WebRequestMethods;

namespace THPTChuyen.Areas.Admin.Controllers
{
    public class GiaoViensController : Controller
    {
        private THPTChuyenVinhEntities db = new THPTChuyenVinhEntities();

        // GET: Admin/GiaoViens
        public IEnumerable<GiaoVien> ListAllGiaoVien(int page, int pageSize)
        {
            return db.GiaoViens.OrderBy(t => t.MaGiaoVien).ToPagedList(page, pageSize);
        }
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var giaoViens = ListAllGiaoVien(page, pageSize);
            return View(giaoViens);
        }

        // GET: Admin/GiaoViens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaoVien giaoVien = db.GiaoViens.Find(id);
            if (giaoVien == null)
            {
                return HttpNotFound();
            }
            return View(giaoVien);
        }

        // GET: Admin/GiaoViens/Create
        public ActionResult Create()
        {
            ViewBag.MaChucVu = new SelectList(db.ChucVus, "MaChucVu", "TenChucVu");
            ViewBag.MaToChuc = new SelectList(db.ToChucs, "MaToChuc", "TenToChuc");
            return View();
        }

        // POST: Admin/GiaoViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGiaoVien,TenGiaoVien,NgaySinh,QueQuan,DiaChi,SDT,Email,TotNghiep,ChuyenNganh,CongTacNam,MaChucVu,MaToChuc")] GiaoVien giaoVien, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.ContentLength > 0)
                {
                    string ten = Path.GetFileNameWithoutExtension(file1.FileName);
                    string duoi = Path.GetExtension(file1.FileName);
                    string daydu = ten + duoi;
                    string path = Path.Combine(Server.MapPath("~/UploadFile/Image"), daydu);
                    file1.SaveAs(path);

                    giaoVien.avatar = daydu;
                }
                db.GiaoViens.Add(giaoVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChucVu = new SelectList(db.ChucVus, "MaChucVu", "TenChucVu", giaoVien.MaChucVu);
            ViewBag.MaToChuc = new SelectList(db.ToChucs, "MaToChuc", "TenToChuc", giaoVien.MaToChuc);
            return View(giaoVien);
        }

        // GET: Admin/GiaoViens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaoVien giaoVien = db.GiaoViens.Find(id);
            if (giaoVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChucVu = new SelectList(db.ChucVus, "MaChucVu", "TenChucVu", giaoVien.MaChucVu);
            ViewBag.MaToChuc = new SelectList(db.ToChucs, "MaToChuc", "TenToChuc", giaoVien.MaToChuc);
            return View(giaoVien);
        }

        // POST: Admin/GiaoViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGiaoVien,TenGiaoVien,NgaySinh,QueQuan,DiaChi,SDT,Email,TotNghiep,ChuyenNganh,CongTacNam,MaChucVu,MaToChuc")] GiaoVien giaoVien, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.ContentLength > 0)
                {
                    string ten = Path.GetFileNameWithoutExtension(file1.FileName);
                    string duoi = Path.GetExtension(file1.FileName);
                    string daydu = ten + duoi;
                    string path = Path.Combine(Server.MapPath("~/UploadFile/Image"), daydu);
                    file1.SaveAs(path);

                    giaoVien.avatar = daydu;
                }
                db.Entry(giaoVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChucVu = new SelectList(db.ChucVus, "MaChucVu", "TenChucVu", giaoVien.MaChucVu);
            ViewBag.MaToChuc = new SelectList(db.ToChucs, "MaToChuc", "TenToChuc", giaoVien.MaToChuc);
            return View(giaoVien);
        }

        // GET: Admin/GiaoViens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaoVien giaoVien = db.GiaoViens.Find(id);
            if (giaoVien == null)
            {
                return HttpNotFound();
            }
            return View(giaoVien);
        }

        // POST: Admin/GiaoViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GiaoVien giaoVien = db.GiaoViens.Find(id);
            db.GiaoViens.Remove(giaoVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

THPTChuyen/Controllers/GiaoVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THPTChuyen.Models;

namespace THPTChuyen.Controllers
{
    
    public class GiaoVienController : Controller
    {
        THPTChuyenVinhEntities THPTChuyen = new THPTChuyenVinhEntities();
        // GET: GiaoVien
        public ActionResult Index(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();

            model.toChuc = (from i in THPTChuyen.ToChucs
                           where i.MaToChuc == id
                           select i).ToList();

            model.giaoVien = (from i in THPTChuyen.GiaoViens
                              join cv in THPTChuyen.ChucVus
                              on i.MaChucVu equals cv.MaChucVu
                              where i.MaToChuc == id
                              select i).ToList();
            return View(model);
        }
        public ActionResult Chitiet(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();

            model.toChuc = (from i in THPTChuyen.ToChucs
                            join gv in THPTChuyen.GiaoViens
                            on i.MaToChuc equals gv.MaToChuc
                            where gv.MaGiaoVien == id
                            select i).ToList();

            model.giaoVien = (from i in THPTChuyen.GiaoViens
                              where i.MaGiaoVien == id
                              select i).ToList();
            return View(model);
        }

    }
}

THPTChuyen/Areas/Admin/Views/GiaoViens/Create.cshtml
@model THPTChuyen.Models.GiaoVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm giáo viên</h2>

@using (Html.BeginForm("Create", "GiaoViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <h6>Họ tên</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenGiaoVien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenGiaoVien, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <h6>Avatar</h6>
        <div class="col-md-10">
            @Html.TextBox("file1", "", new { type = "file" })
        </div>
    </div>
    <div class="form-group">
        <h6>Ngày sinh</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Quê quán</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Địa chỉ</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Điện thoại</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Email</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Tốt nghiệp</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotNghiep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotNghiep, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Chuyên ngành</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ChuyenNganh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Công tác năm</h6>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongTacNam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongTacNam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Chúc vụ</h6>
        <div class="col-md-10">
            @Html.DropDownList("MaChucVu", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaChucVu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h6>Bộ môn</h6>
        <div class="col-md-10">
            @Html.DropDownList("MaToChuc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaToChuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-default" /> &emsp;
            <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
        </div>
    </div>
</div>
}

THPTChuyen/Areas/Admin/Views/GiaoViens/Delete.cshtml
@model THPTChuyen.Models.GiaoVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h3>Bạn có chắc chăn muốn xóa không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ tên:  @Html.DisplayFor(model => model.TenGiaoVien)
        </dt>
        <dt>
            <img src="~/UploadFile/Image/@Html.DisplayFor(model => model.avatar)" style="height:300px; width: 400px" />
        </dt>
        <dt>
            Ngày sinh: @Html.DisplayFor(model => model.NgaySinh)
        </dt>
        <dt>
            Quê quán: @Html.DisplayFor(model => model.QueQuan)
        </dt>

        <dt>
            Địa chỉ: @Html.DisplayFor(model => model.DiaChi)
        </dt>

        <dt>
            Điện thoại: @Html.DisplayFor(model => model.SDT)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Email): @Html.DisplayFor(model => model.Email)
        </dt>

        <dt>
            Tốt nghiệp: @Html.DisplayFor(model => model.TotNghiep)
        </dt>

        <dt>
            Chuyên ngành: @Html.DisplayFor(model => model.ChuyenNganh)
        </dt>

        <dt>
            Công tác năm: @Html.DisplayFor(model => model.CongTacNam)
        </dt>
        <dt>
            Chức vụ:  @Html.DisplayFor(model => model.ChucVu.TenChucVu)
        </dt>

        <dt>
            Tổ chức: @Html.DisplayFor(model => model.ToChuc.TenToChuc)
        </dt>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> &emsp;
            <button type="submit", class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
            
        </div>
    }
</div>

THPTChuyen/Areas/Admin/Views/GiaoViens/Details.cshtml
@model THPTChuyen.Models.GiaoVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Giáo viên</h2>

<div>
    <h4>@Html.DisplayFor(model => model.TenGiaoVien)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ngày sinh: @Html.DisplayFor(model => model.NgaySinh)
        </dt>
        <br />
        <dt>
            Quê quán: @Html.DisplayFor(model => model.QueQuan)
        </dt>
        <br />
        <dt>
            Địa chỉ: @Html.DisplayFor(model => model.DiaChi)
        </dt>
        <br />
        <dt>
            Điện thoại: @Html.DisplayFor(model => model.SDT)
        </dt>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Email): @Html.DisplayFor(model => model.Email)
        </dt>
        <br />
        <dt>
            Tốt nghiệp năm: @Html.DisplayFor(model => model.TotNghiep)
        </dt>
        <br />
        <dt>
            Chuyên ngành: @Html.DisplayFor(model => model.ChuyenNganh)
        </dt>
        <br />
        <dt>
            Công tác năm: @Html.DisplayFor(model => model.CongTacNam)
        </dt>
        <br />
        <dt>
            Chúc vụ: @Html.DisplayFor(model => model.ChucVu.TenChucVu)
        </dt>
        <br />
        <dt>
            Tổ chức: @Html.DisplayFor(model => model.ToChuc.TenToChuc)
        </dt>
        <br />
    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">@Html.ActionLink("Sửa", "Edit", new { id = Model.MaGiaoVien })</button>
            &emsp;
            <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
        </div>
    </div>
</p>

THPTChuyen/Areas/Admin/Views/GiaoViens/Edit.cshtml
@model THPTChuyen.Models.GiaoVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa giáo viên</h2>

@using (Html.BeginForm("Edit", "GiaoViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaGiaoVien)

    <div class="form-group">
        Họ tên
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenGiaoVien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenGiaoVien, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        Avatar
        <div class="col-md-10">
            @Html.TextBox("file1", "", new { type = "file" })
        </div>
    </div>
    <div class="form-group">
        Ngày sinh
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Quê quán
        <div class="col-md-10">
            @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Địa chỉ
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Điện thoại
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Email
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Tốt nghiệp năm
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotNghiep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotNghiep, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Chuyên ngành
        <div class="col-md-10">
            @Html.EditorFor(model => model.ChuyenNganh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Công tác năm
        <div class="col-md-10">
            @Html.EditorFor(model => model.CongTacNam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CongTacNam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Chức vụ
        <div class="col-md-10">
            @Html.DropDownList("MaChucVu", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaChucVu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Tổ chức
        <div class="col-md-10">
            @Html.DropDownList("MaToChuc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaToChuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" /> &emsp;
            <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
        </div>
    </div>
</div>
}

THPTChuyen/Areas/Admin/Views/GiaoViens/Index.cshtml
@model PagedList.IPagedList<THPTChuyen.Models.GiaoVien>
@using PagedList.Mvc

@{
    ViewBag.Title = "Giáo viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Giáo viên</h2>
<style>
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        width: 100%;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
</style>
<p>
    <button style="border: 1px solid #cb0c9f; border-radius: 5px; padding: 6px 12px; background: white ">@Html.ActionLink("Thêm giáo viên", "Create")</button>
</p>
<table class="styled-table">
    <thead>
        <tr>
            <th>
                Họ tên
            </th>
            <th>
                Avatar
            </th>
            <th>
                Điện thoại
            </th>
            <th>
                Email
            </th>
            <th>
                Chức vụ
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenGiaoVien)
                </td>
                <td>
                    <img src="~/UploadFile/Image/@Html.DisplayFor(modelItem => item.avatar)" style="height:70px;width:60px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChucVu.TenChucVu)
                </td>

                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MaGiaoVien }) |
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.MaGiaoVien }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MaGiaoVien })
                </td>
            </tr>
        }
    </tbody>

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))