THPTChuyen/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaLoaiTin { get; set; }
    
        public virtual LoaiTin LoaiTin { get; set; }
    }
}

THPTChuyen/Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using THPTChuyen.Models;
using PagedList.Mvc;
using PagedList;

namespace THPTChuyen.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private THPTChuyenVinhEntities db = new THPTChuyenVinhEntities();

        // GET: Admin/TinTucs
        public IEnumerable<TinTuc> ListAllTinTuc(int page, int pageSize)
        {
            return db.TinTucs.OrderBy(t=>t.MaTinTuc).ToPagedList(page, pageSize);
        }
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var tinTucs = ListAllTinTuc(page, pageSize);
            return View(tinTucs);
        }

        // GET: Admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiTin = new SelectList(db.LoaiTins, "MaLoaiTin", "TenLoai");
            return View();
        }

        // POST: Admin/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTinTuc,TieuDe,HinhAnh,NoiDung,MaLoaiTin")] TinTuc tinTuc, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if(file1 != null && file1.ContentLength>0)
                {
                    string ten = Path.GetFileNameWithoutExtension(file1.FileName);
                    string duoi = Path.GetExtension(file1.FileName);
                    string daydu = ten + DateTime.Now.ToString("HHmmss") + duoi;
                    string path = Path.Combine(Server.MapPath("~/images"), daydu);
                    file1.SaveAs(path);
                    
                    tinTuc.HinhAnh = daydu;
                }
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiTin = new SelectList(db.LoaiTins, "MaLoaiTin", "TenLoai", tinTuc.MaLoaiTin);
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiTin = new SelectList(db.LoaiTins, "MaLoaiTin", "TenLoai", tinTuc.MaLoaiTin);
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TinTuc tinTuc)
        {
            var tintuc = db.TinTucs.Find(tinTuc.MaTinTuc);
            if (String.IsNullOrEmpty(tinTuc.TieuDe))
            {               
 
                return View(tinTuc);
            }
            tintuc.NoiDung = tinTuc.NoiDung;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

THPTChuyen/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THPTChuyen.Models;

namespace THPTChuyen.Controllers
{
    public class TinTucController : Controller
    {
        THPTChuyenVinhEntities THPTChuyen = new THPTChuyenVinhEntities();
        // GET: TinTuc
        public ActionResult Index(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();

            model.tintuc = (from i in THPTChuyen.TinTucs
                            join lt in THPTChuyen.LoaiTins
                            on i.MaLoaiTin equals lt.MaLoaiTin
                            where lt.MaLoaiTin == id
                            select i).ToList();

            model.loaitin = (from i in THPTChuyen.LoaiTins
                             where i.MaLoaiTin == id
                             select i).ToList();

            return View(model);
        }
        public ActionResult Chitiet(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();

            model.tintuc= (from item in THPTChuyen.TinTucs
                           where item.MaTinTuc == id
                           select item).ToList();
            
            model.loaitin = (from lt in THPTChuyen.LoaiTins
                             join tt in THPTChuyen.TinTucs
                             on lt.MaLoaiTin equals tt.MaLoaiTin
                             where tt.MaTinTuc == id
                             select lt).ToList();

            return View(model);
        }
    }
}

THPTChuyen/Areas/Admin/Views/TinTucs/Create.cshtml
@model THPTChuyen.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm tin tức</h2>

@using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new {enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <h6>Tiêu đề</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Hình ảnh</h6>
            <div class="col-md-10">
                @Html.TextBox("file1", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            <h6>Nội dung</h6>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.NoiDung, new { htmlAttributes = new { @class = "ckeditor" }, id="noiDung" })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Loại</h6>
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiTin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiTin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" /> &emsp;
                <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
            </div>
        </div>
    </div>
}
@section scripts{
    <script>
        CKEDITOR.replace("noiDung");
    </script>
    
}

THPTChuyen/Areas/Admin/Views/TinTucs/Delete.cshtml
@model THPTChuyen.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h3>Bạn có chắc chăn muốn xóa không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tiêu đề: @Html.DisplayFor(model => model.TieuDe)
        </dt>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            <img src="~/images/@Html.DisplayFor(model => model.HinhAnh)" style="height:300px; width: 400px" />
        </dd>

        <dt>
            Nội dung
        </dt>

        <dd>
            @Html.Raw(Model.NoiDung)
        </dd>

        <dt>
            Thể loại: @Html.DisplayFor(model => model.LoaiTin.TenLoai)
        </dt>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> &emsp;
            <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
        </div>
    }
</div>

THPTChuyen/Areas/Admin/Views/TinTucs/Details.cshtml
@model THPTChuyen.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tiêu đề
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            
            <img src="~/images/@Html.DisplayFor(model => model.HinhAnh)" style="height:300px; width: 400px"/>
        </dd>

        <dt>
            Nội dung
        </dt>

        <dd style="color:black">
            @Html.Raw(Model.NoiDung)
        </dd>

        <dt>
            Thể loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTin.TenLoai)
        </dd>

    </dl>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <button type="submit" class="btn btn-default">@Html.ActionLink("Sửa ", "Edit", new { id = Model.MaTinTuc })</button> &emsp;
        <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
    </div>
</div>

THPTChuyen/Areas/Admin/Views/TinTucs/Edit.cshtml
@model THPTChuyen.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa tin tức</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTinTuc)

        <div class="form-group">
            Tiêu đề
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Hình ảnh
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Nội dung
            <div class="col-md-10">
                <textarea class="form-control" name="NoiDung" id="noiDung">@Model.NoiDung</textarea>
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Thể loại
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiTin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiTin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" /> &emsp;
                <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
            </div>
        </div>
    </div>
}
@section scripts{
    <script>
        CKEDITOR.replace("noiDung");
    </script>

}

THPTChuyen/Areas/Admin/Views/TinTucs/Index.cshtml
@model PagedList.IPagedList<THPTChuyen.Models.TinTuc>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tin tức</h2>
<style>
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        width: 100%;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

        .styled-table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }

        .styled-table tbody tr:last-of-type {
            border-bottom: 2px solid #009879;
        }
            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
</style>
<p>
    <button style="border: 1px solid #cb0c9f; border-radius: 5px; padding: 6px 12px; background: white "> @Html.ActionLink("Thêm  mới", "Create")</button>
    <div class="row">
        <div class="col-lg-12">
            <table class="styled-table">
                <thead>
                    <tr>
                        <th>
                            Tiêu đề
                        </th>
                        <th>
                            Hình ảnh
                        </th>
                        <th>
                            Thể loại
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TieuDe)
                            </td>
                            <td>
                                <img src="~/images/@Html.DisplayFor(modelItem => item.HinhAnh)" style="height:50px;width:100px" />

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LoaiTin.TenLoai)
                            </td>
                            <td style="width:150px">
                                @Html.ActionLink("Sửa", "Edit", new { id = item.MaTinTuc }) |
                                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaTinTuc }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.MaTinTuc })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

        </div>

    </div>