THPTChuyen/Models/VanBan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int MaVanBan { get; set; }
        public string TieuDe { get; set; }
        public string KiHieu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<int> MaLoaiVanBan { get; set; }
        public string NguoiKy { get; set; }
        public string DuongDan { get; set; }
    
        public virtual LoaiVanBan LoaiVanBan { get; set; }
    }
}

THPTChuyen/Areas/Admin/Controllers/VanBansController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using THPTChuyen.Models;
using PagedList.Mvc;

namespace THPTChuyen.Areas.Admin.Controllers
{
    public class VanBansController : Controller
    {
        private THPTChuyenVinhEntities db = new THPTChuyenVinhEntities();

        // GET: Admin/VanBans
        public IEnumerable<VanBan> ListAllVanban(int page, int pageSize)
        {
            return db.VanBans.OrderBy(t => t.MaVanBan).ToPagedList(page, pageSize);
        }
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var vanBans = ListAllVanban(page, pageSize);
            return View(vanBans);
        }

        // GET: Admin/VanBans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VanBan vanBan = db.VanBans.Find(id);
            if (vanBan == null)
            {
                return HttpNotFound();
            }
            return View(vanBan);
        }

        // GET: Admin/VanBans/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiVanBan = new SelectList(db.LoaiVanBans, "MaLoaiVanBan", "TenLoaiVanBan");
            return View();
        }

        // POST: Admin/VanBans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaVanBan,TieuDe,KiHieu,NgayBanHanh,NgayHieuLuc,MaLoaiVanBan,NguoiKy,DuongDan")] VanBan vanBan, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.ContentLength > 0)
                {
                    string ten = Path.GetFileNameWithoutExtension(file1.FileName);
                    string duoi = Path.GetExtension(file1.FileName);
                    string daydu = ten + duoi;
                    string path = Path.Combine(Server.MapPath("~/UploadFile/File/"), daydu);
                    file1.SaveAs(path);

                    vanBan.DuongDan = daydu;
                }
                db.VanBans.Add(vanBan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiVanBan = new SelectList(db.LoaiVanBans, "MaLoaiVanBan", "TenLoaiVanBan", vanBan.MaLoaiVanBan);
            return View(vanBan);
        }

        // GET: Admin/VanBans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VanBan vanBan = db.VanBans.Find(id);
            if (vanBan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiVanBan = new SelectList(db.LoaiVanBans, "MaLoaiVanBan", "TenLoaiVanBan", vanBan.MaLoaiVanBan);
            return View(vanBan);
        }

        // POST: Admin/VanBans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaVanBan,TieuDe,KiHieu,NgayBanHanh,NgayHieuLuc,MaLoaiVanBan,NguoiKy,DuongDan")] VanBan vanBan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vanBan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiVanBan = new SelectList(db.LoaiVanBans, "MaLoaiVanBan", "TenLoaiVanBan", vanBan.MaLoaiVanBan);
            return View(vanBan);
        }

        // GET: Admin/VanBans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VanBan vanBan = db.VanBans.Find(id);
            if (vanBan == null)
            {
                return HttpNotFound();
            }
            return View(vanBan);
        }

        // POST: Admin/VanBans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VanBan vanBan = db.VanBans.Find(id);
            db.VanBans.Remove(vanBan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

THPTChuyen/Controllers/VanBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THPTChuyen.Models;

namespace THPTChuyen.Controllers
{
    public class VanBanController : Controller
    {
        // GET: VanBan
        private THPTChuyenVinhEntities THPTChuyen = new THPTChuyenVinhEntities();

        // GET: Admin/VanBans
        public ActionResult Index(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();

            model.loaivb = (from i in THPTChuyen.LoaiVanBans
                            where i.MaLoaiVanBan == id
                            select i).ToList();

            model.listVanban = (from i in THPTChuyen.VanBans
                                where i.MaLoaiVanBan == id
                          select i).ToList();

            return View(model);
        }
        public ActionResult Chitiet(int id)
        {
            HomeModel model = new HomeModel();
            model.listLoaivanban = THPTChuyen.LoaiVanBans.ToList();

            model.listLoaitintuc = (from item in THPTChuyen.LoaiTins
                                    select item).ToList();

            model.listToChuc = THPTChuyen.ToChucs.ToList();
            model.listVanban = (from i in THPTChuyen.VanBans
                                where i.MaVanBan == id
                                select i).ToList();
            return View(model);
        }
    }
}

THPTChuyen/Areas/Admin/Views/VanBans/Create.cshtml
@model THPTChuyen.Models.VanBan

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm văn bản</h2>

@using (Html.BeginForm("Create", "VanBans", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Tiêu đề
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Kí hiệu
            <div class="col-md-10">
                @Html.EditorFor(model => model.KiHieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KiHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Ngày ban hành
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBanHanh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.NgayBanHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Ngày hiệu lực
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayHieuLuc, new { htmlAttributes = new { @class = "form-control" , type= "date"}  })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                @Html.ValidationMessageFor(model => model.NgayHieuLuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Loại văn bản
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiVanBan", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiVanBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Người ký
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiKy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiKy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Nội dung
            <div class="col-md-10">
                @Html.TextBox("file1", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" /> &emsp;
                <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
            </div>
        </div>
    </div>
}

THPTChuyen/Areas/Admin/Views/VanBans/Delete.cshtml
@model THPTChuyen.Models.VanBan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h3>Bạn chắc chắn muốn xóa không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tiêu đề: @Html.DisplayFor(model => model.TieuDe)
        </dt>

        <dt>
            Kí hiệu: @Html.DisplayFor(model => model.KiHieu)
        </dt>

        <dt>
            Ngày ban hành: @Html.DisplayFor(model => model.NgayBanHanh)
        </dt>

        <dt>
            Ngày hiệu lực: @Html.DisplayFor(model => model.NgayHieuLuc)
        </dt>
        <dt>
            Người ký: @Html.DisplayFor(model => model.NguoiKy)
        </dt>

        <dt>
            <iframe style="width:600px; height:700px" src="~/UploadFile/File/@Model.DuongDan"></iframe>
        </dt>

        <dt>
            Thể loại: @Html.DisplayFor(model => model.LoaiVanBan.TenLoaiVanBan)
        </dt>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> &emsp;
            <button type="submit", class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
        </div>
    }
</div>

THPTChuyen/Areas/Admin/Views/VanBans/Edit.cshtml
@model THPTChuyen.Models.VanBan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa văn bản</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaVanBan)

        <div class="form-group">
            <h6 class="control-label col-md-2">Tiêu đề</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6 class="control-label col-md-2">Ký hiệu</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.KiHieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KiHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Ngày ban hành</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBanHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayBanHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Ngày hiệu lực</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayHieuLuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayHieuLuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Loại văn bản</h6>
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiVanBan", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiVanBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Người ký</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiKy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiKy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h6>Tệp</h6>
            <div class="col-md-10">
                <iframe src="~/UploadFile/File/@Model.DuongDan"></iframe>
                @*@Html.EditorFor(model => model.DuongDan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DuongDan, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" /> &emsp;
                <button type="submit" class="btn btn-default">@Html.ActionLink("Trở về", "Index")</button>
            </div>
        </div>
    </div>
}

THPTChuyen/Areas/Admin/Views/VanBans/Index.cshtml
@model PagedList.IPagedList<THPTChuyen.Models.VanBan>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Văn bản</h2>
<style>
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        width: 100%;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
</style>
<p>
    <button style="border: 1px solid #cb0c9f; border-radius: 5px; padding: 6px 12px; background: white ">@Html.ActionLink("Thêm văn bản", "Create")</button>
</p>
<table class="styled-table">
    <thead>
        <tr>
            <th>
                Tiêu đề
            </th>
            <th>
                Số hiệu
            </th>
            <th>
                Ngày ban hành
            </th>
            <th>
                Ngày hiệu lực
            </th>
            <th>
                Người ký
            </th>
            <th>
                Tệp
            </th>
            <th>
                Thể loại
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TieuDe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KiHieu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayBanHanh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayHieuLuc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiKy)
                </td>
                <td>
                    <a href="~/UploadFile/File/@Html.DisplayFor(modelItem => item.DuongDan)" download="@Html.DisplayFor(modelItem => item.DuongDan)"><i class="fa-solid fa-download"></i></a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoaiVanBan.TenLoaiVanBan)
                </td>
                <td style="width:100px">
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MaVanBan }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MaVanBan })
                </td>
            </tr>
        }
    </tbody>

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))